version: "3"

networks:
  backend:

services:
  appDetector:
    image: python-dev:latest
    container_name: python-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app:delegated
    network_mode: "host"
    ports:
      - "8080:80"
  db:
    image: mongo
    container_name: db_development
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1111
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - backend

  flask:
    image: python-dev:latest
    container_name: flask-dev
    command: [ "python", "api.py" ]
    depends_on:
      - db
    network_mode: "host"
    volumes:
      - .:/app:delegated
    ports:
      - "5000:5000"

  web:
    image: python-dev:latest
    container_name: Django-dev
    command: [ "python", "myweb/manage.py", "runserver" ]
    network_mode: "host"
    volumes:
      - .:/app:delegated
    ports:
      - "8000:8000"


