version: "3"

networks:
  backend:

services:
  db:
    image: mysql:5.7
    container_name: db_development
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    networks:
      - backend

