version: "3"

networks:
  backend:

services:
  appDetector:
    image: python-dev:latest
    container_name: python-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    volumes:
      - .:/app:delegated
    network_mode: "host"
    ports:
      - "8080:80"
  db:
    image: mysql:5.7
    container_name: db_development
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"
    networks:
      - backend

